# Generated by Django 2.1 on 2018-08-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomboomgame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_players', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Grey', 'Grey'), ('Green', 'Green'), ('Purple', 'Purple')], max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cardset',
            name='cards',
            field=models.ManyToManyField(to='boomboomgame.Card'),
        ),
    ]
