# Generated by Django 2.1 on 2018-09-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomboomgame', '0002_auto_20180813_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_swap',
            field=models.BooleanField(default=False),
        ),
    ]
