# Generated by Django 2.1 on 2018-10-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomboomgame', '0003_card_card_swap'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='buried_cards',
            field=models.ManyToManyField(related_name='buried_cards', to='boomboomgame.Card'),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='cards',
            field=models.ManyToManyField(related_name='non_buried_cards', to='boomboomgame.Card'),
        ),
    ]
