# Generated by Django 2.1 on 2018-10-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomboomgame', '0004_auto_20181004_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='buried_cards',
            field=models.ManyToManyField(blank=True, related_name='buried_cards', to='boomboomgame.Card'),
        ),
    ]
