var imagePathObject = {
    'Blue_Agent.png': require('./images/Blue_Agent.png'),
    'Blue_Bouncer.png': require('./images/Blue_Bouncer.png'),
    'Blue_Criminal.png': require('./images/Blue_Criminal.png'),
    'Blue_Dealer.png': require('./images/Blue_Dealer.png'),
    'Blue_Enforcer.png': require('./images/Blue_Enforcer.png'),
    'Blue_Fool.png': require('./images/Blue_Fool.png'),
    'Blue_Mayor.png': require('./images/Blue_Mayor.png'),
    'Blue_Negotiator.png': require('./images/Blue_Negotiator.png'),
    'Blue_Psychologist.png': require('./images/Blue_Psychologist.png'),
    'Blue_Shy_Guy.png': require('./images/Blue_Shy_Guy.png'),
    'Blue_Spy.png': require('./images/Blue_Spy.png'),
    'Blue_Team.png': require('./images/Blue_Team.png'),
    'Blue_Team_QdEbKRZ.png': require('./images/Blue_Team_QdEbKRZ.png'),
    'Bomber.png': require('./images/Bomber.png'),
    'Changer.png': require('./images/Changer.png'),
    'Doctor.png': require('./images/Doctor.png'),
    'Engineer.png': require('./images/Engineer.png'),
    'Grey_Ahab.png': require('./images/Grey_Ahab.png'),
    'Grey_Intern.png': require('./images/Grey_Intern.png'),
    'Grey_Mistress.png': require('./images/Grey_Mistress.png'),
    'Grey_Moby.png': require('./images/Grey_Moby.png'),
    'Grey_Rival.png': require('./images/Grey_Rival.png'),
    'Grey_Survivor.png': require('./images/Grey_Survivor.png'),
    'Grey_Team.png': require('./images/Grey_Team.png'),
    'Grey_Victim.png': require('./images/Grey_Victim.png'),
    'Grey_Wife.png': require('./images/Grey_Wife.png'),
    'Hot_Potato.png': require('./images/Hot_Potato.png'),
    'Leprechaun.png': require('./images/Leprechaun.png'),
    'Martyr.png': require('./images/Martyr.png'),
    'Nurse.png': require('./images/Nurse.png'),
    'President.png': require('./images/President.png'),
    'Presidents_Daughter.png': require('./images/Presidents_Daughter.png'),
    'Red_Agent.png': require('./images/Red_Agent.png'),
    'Red_Bouncer.png': require('./images/Red_Bouncer.png'),
    'Red_Criminal.png': require('./images/Red_Criminal.png'),
    'Red_Dealer.png': require('./images/Red_Dealer.png'),
    'Red_Enforcer.png': require('./images/Red_Enforcer.png'),
    'Red_Psychologist.png': require('./images/Red_Psychologist.png'),
    'Red_Fool.png': require('./images/Red_Fool.png'),
    'Red_Mayor.png': require('./images/Red_Mayor.png'),
    'Red_Negotiator.png': require('./images/Red_Negotiator.png'),
    'Red_Shy_Guy.png': require('./images/Red_Shy_Guy.png'),
    'Red_Spy.png': require('./images/Red_Spy.png'),
    'Red_Team.png': require('./images/Red_Team.png'),
    'Red_Team_cO4aIOJ.png': require('./images/Red_Team_cO4aIOJ.png'),
    'Tinkerer.png': require('./images/Tinkerer.png'),
    'Zombie.png': require('./images/Zombie.png'),
    'RED': require('./images/Red_Team.png'),
    'BLUE': require('./images/Blue_Team.png'),
    'GREY': require('./images/Grey_Team.png')
}


export const imagePaths = imagePathObject;